/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author Admin
 */
public class GUI extends javax.swing.JFrame {
    
public static double Add(double num1, double num2){
    return num1 + num2;
}
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    double num1, num2,num3, num4,result;
    String opr;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        EquationClear = new javax.swing.JButton();
        PlusMinus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        point = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        floorButton = new javax.swing.JButton();
        ceilButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        intButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        moduloButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        squareRoot = new javax.swing.JToggleButton();
        cubeRoot = new javax.swing.JButton();
        Summation = new javax.swing.JButton();
        XY = new javax.swing.JButton();
        XYZ = new javax.swing.JButton();
        product = new javax.swing.JButton();
        doubleSummation = new javax.swing.JButton();
        doubleProduct = new javax.swing.JButton();
        set = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        logTwoX = new javax.swing.JButton();
        logX = new javax.swing.JButton();
        factorialAddition = new javax.swing.JButton();
        factorialDivision = new javax.swing.JButton();
        XTimesY = new javax.swing.JButton();
        XPlusY = new javax.swing.JButton();
        XRaisedY = new javax.swing.JButton();
        CTimesX = new javax.swing.JButton();
        XPlusC = new javax.swing.JButton();
        XRaisedC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 90));

        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 60));

        EquationClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EquationClear.setText("AC");
        EquationClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquationClearActionPerformed(evt);
            }
        });
        getContentPane().add(EquationClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 60));

        PlusMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlusMinus.setText("+/-");
        PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(PlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 70, 60));

        plus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 70, 60));

        seven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 60));

        eight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 60));

        nine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 70, 60));

        minus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 60));

        four.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 60));

        five.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, 60));

        six.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 70, 60));

        multiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 70, 60));

        one.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 70, 60));

        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, 60));

        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 70, 60));

        divide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        divide.setText("÷");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 70, 60));

        zero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 60));

        point.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });
        getContentPane().add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 60));

        equals.setBackground(new java.awt.Color(0, 204, 204));
        equals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equals.setForeground(new java.awt.Color(0, 0, 0));
        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        getContentPane().add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, 60));

        floorButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        floorButton.setText("FLR");
        floorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(floorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, 60));

        ceilButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ceilButton.setText("CEIL");
        ceilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ceilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 70, 60));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 40));

        intButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        intButton.setText("INT");
        intButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intButtonActionPerformed(evt);
            }
        });
        getContentPane().add(intButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 70, 60));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("//");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, 60));

        moduloButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduloButton.setText("%");
        moduloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moduloButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, 60));

        factorialButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        factorialButton.setText("N!");
        factorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(factorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 70, 60));

        squareRoot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        squareRoot.setText("√");
        squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootActionPerformed(evt);
            }
        });
        getContentPane().add(squareRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, 60));

        cubeRoot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cubeRoot.setText("3√");
        getContentPane().add(cubeRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 70, 60));

        Summation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Summation.setText("∑");
        Summation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummationActionPerformed(evt);
            }
        });
        getContentPane().add(Summation, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 70, 60));

        XY.setText("x^y");
        getContentPane().add(XY, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 70, 60));

        XYZ.setText("x^y^z");
        getContentPane().add(XYZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 70, 60));

        product.setText("∏");
        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 70, 60));

        doubleSummation.setText("∑∑");
        getContentPane().add(doubleSummation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 100, 60));

        doubleProduct.setText("∏∏");
        getContentPane().add(doubleProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 100, 60));

        set.setText("SET");
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 280, 70));

        aButton.setText("A");
        getContentPane().add(aButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 70, 60));

        bButton.setText("B");
        getContentPane().add(bButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 70, 60));

        cButton.setText("C");
        getContentPane().add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 70, 60));

        dButton.setText("D");
        getContentPane().add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 70, 60));

        logTwoX.setText("log2 x");
        getContentPane().add(logTwoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 70));

        logX.setText("log x");
        getContentPane().add(logX, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 100, 70));

        factorialAddition.setText("a! + b!");
        factorialAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialAdditionActionPerformed(evt);
            }
        });
        getContentPane().add(factorialAddition, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 100, 60));

        factorialDivision.setText("a! / b!");
        getContentPane().add(factorialDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 100, 60));

        XTimesY.setText("xy");
        getContentPane().add(XTimesY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 50));

        XPlusY.setText("x+y");
        XPlusY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XPlusYActionPerformed(evt);
            }
        });
        getContentPane().add(XPlusY, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, 50));

        XRaisedY.setText("x^y");
        getContentPane().add(XRaisedY, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, 50));

        CTimesX.setText("Cx");
        getContentPane().add(CTimesX, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, 50));

        XPlusC.setText("x+C");
        XPlusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XPlusCActionPerformed(evt);
            }
        });
        getContentPane().add(XPlusC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, 50));

        XRaisedC.setText("x^c");
        getContentPane().add(XRaisedC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        
        opr = "+";
    }//GEN-LAST:event_plusActionPerformed

    private void PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusMinusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        if(num1>0){
            result = num1 * -1;
            jTextField1.setText(Double.toString(result));
        }
        
    }//GEN-LAST:event_PlusMinusActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        
        opr = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        
        opr = "*";
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        
        opr = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(jTextField1.getText());
        num3 = Double.parseDouble(jTextField1.getText());
        
        if(opr == "+")
        {
            result = num1 + num2;
            jTextField1.setText(Double.toString(result));
        }
        else if(opr == "-")
        {
            result = num1 - num2;
            jTextField1.setText(Double.toString(result));
        }
        else if(opr == "*")
        {
            result = num1 * num2;
            jTextField1.setText(Double.toString(result));
        }
        else if(opr == "/")
        {
            result = num1 / num2;
            jTextField1.setText(Double.toString(result));
        }
        else if(opr == "mod")
        {
            result = num1 % num2;
            jTextField1.setText(Double.toString(result));
            jTextField2.setText("");
        } 
    }//GEN-LAST:event_equalsActionPerformed

    private void EquationClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquationClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_EquationClearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String backspace = null;
        
        if(jTextField1.getText().length() > 0)
        {
            StringBuilder s= new StringBuilder(jTextField1.getText());
            
            s.deleteCharAt(jTextField1.getText().length() - 1);
            backspace = s.toString();
            jTextField1.setText(backspace);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_pointActionPerformed

    private void floorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorButtonActionPerformed
        // TODO add your handling code here:
       num1 = Double.parseDouble(jTextField1.getText());
       
       result = Math.floor(num1);
       jTextField1.setText(Double.toString(result));             
    }//GEN-LAST:event_floorButtonActionPerformed

    private void ceilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilButtonActionPerformed
        // TODO add your handling code here:
       num1 = Double.parseDouble(jTextField1.getText());
       
       result = Math.ceil(num1);
       jTextField1.setText(Double.toString(result));
    }//GEN-LAST:event_ceilButtonActionPerformed

    private void intButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        int integer = (int)Math.floor(num1);
        jTextField1.setText(String.valueOf(integer));
    }//GEN-LAST:event_intButtonActionPerformed

    private void moduloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloButtonActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(jTextField2.getText() + "%");
       
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "mod";
    }//GEN-LAST:event_moduloButtonActionPerformed

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        double product = 1;
        if (num1<0)
        {
            jTextField1.setText("Invalid Number");
        }else
        {
            for (double  i = num1; i > 0; i--) {
                product = product * i;
                jTextField1.setText(Double.toString(product));
             }
             
        }
    }//GEN-LAST:event_factorialButtonActionPerformed

    private void squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        double integer = Math.sqrt(num1);
        jTextField1.setText(String.valueOf(integer));
    }//GEN-LAST:event_squareRootActionPerformed

    private void SummationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SummationActionPerformed

    private void XPlusYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XPlusYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XPlusYActionPerformed

    private void factorialAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialAdditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factorialAdditionActionPerformed

    private void XPlusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XPlusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XPlusCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CTimesX;
    private javax.swing.JButton EquationClear;
    private javax.swing.JButton PlusMinus;
    private javax.swing.JButton Summation;
    private javax.swing.JButton XPlusC;
    private javax.swing.JButton XPlusY;
    private javax.swing.JButton XRaisedC;
    private javax.swing.JButton XRaisedY;
    private javax.swing.JButton XTimesY;
    private javax.swing.JButton XY;
    private javax.swing.JButton XYZ;
    private javax.swing.JButton aButton;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton ceilButton;
    private javax.swing.JButton cubeRoot;
    private javax.swing.JButton dButton;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton doubleProduct;
    private javax.swing.JButton doubleSummation;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton factorialAddition;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton factorialDivision;
    private javax.swing.JButton five;
    private javax.swing.JButton floorButton;
    private javax.swing.JButton four;
    private javax.swing.JButton intButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton logTwoX;
    private javax.swing.JButton logX;
    private javax.swing.JButton minus;
    private javax.swing.JButton moduloButton;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton product;
    private javax.swing.JButton set;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JToggleButton squareRoot;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}

